# title of website
title: work

# description of website
description: r-hou's navigation site

# favicon of website
favicon: "https://github.com/r-hou.png?size=40"

# your website url
url: https://r-hou.github.io/work/

# github profile url
github: "https://github.com/r-hou"

# footer message
footer: © 2021-2021 @r-hou

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: OTC Trades
          description: Check orders
          url: http://ny5ms1:8503
        - name: DM Back test
          description: DM backtest stats
          url: https://ny5ms1:8504/?app=Paper+Trading+-+irs_dm_open
        - name: UI中国
          description: 图形交互与界面设计交流、作品展示、学习平台。
          url: http://www.ui.cn/
    - name: 界面灵感
      sites:
        - name: 咕噜素材
          description: 质量很高的设计素材网站（推荐）
          url: https://www.gulusucai.com/
        - name: 设计周刊
          description: 最新设计资讯（每天更新）
          url: https://www.shejizhoukan.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
        - name: 电鸭社区
          description: 国内最早的远程工作社区，也是互联网工作者们的聚集地，非常适合设计开发小伙伴关注
          url: https://eleduck.com/